---
# tasks file for sonarqube

- name: Update system package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Set max_map
  ansible.builtin.command:
    cmd: sysctl -w vm.max_map_count=262144

- name: Set file max
  ansible.builtin.command:
    cmd: sysctl -w fs.file-max=65536

- name: Add max limits
  ansible.builtin.lineinfile:
    path: /etc/security/limits.conf
    line:
      - "sonarqube   -   nofile   65536"
      - "sonarqube   -   nproc    4096"
    create: yes

- name: Add PPA repository 
  ansible.builtin.apt_repository:
    repo: ppa:linuxuprising/java

- name: Install required packages
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - python3-dev
      - libpq-dev
    state: present

- name: Install setuptools
  ansible.builtin.pip:
    name: setuptools
    state: latest

- name: Upgrade pip
  ansible.builtin.pip:
    name: pip
    state: latest

- name: Install pip dependencies
  ansible.builtin.pip:
    name: psycopg2
    executable: pip3

- name: Install Java 17
  ansible.builtin.apt:
    name:
      - openjdk-17-jdk
      - openjdk-17-jre
    state: present
    allow_unauthenticated: yes

- import_tasks: postgresql.yml

- name: Ensure group sonar exists
  ansible.builtin.group:
    name: sonar
    state: present

- import_tasks: sonarqube-setup.yml

- name: Start and enable sonarqube
  ansible.builtin.systemd:
    name: sonar
    state: started
    enabled: yes
