---
- name: Add PostgreSQL repo to the repo list
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pgdg.list
    line: "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main"
    create: yes

- name: Download PostgreSQL software key
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Install PostgreSQL
  ansible.builtin.apt:
    pkg:
      - postgresql
      - postgresql-contrib
    state: present

- name: Start and enable PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes

  # If PostgreSQL was restarted, wait for it to be ready before proceeding
  async: 300
  poll: 0
  become: yes
  become_user: postgres
  ignore_errors: yes
  register: postgres_restart

- name: Create password for user postgres
  ansible.builtin.user:
    name: postgres
    group: postgres
    password: postgres

- name: Create a new database sonarqubedb
  become_user: postgres
  community.postgresql.postgresql_db:
    name: sonarqube
    encoding: UTF-8

- name: Create user sonarqube
  become_user: postgres
  community.postgresql.postgresql_user:
    db: sonarqube
    name: sonar
    password: sonar
    priv: "ALL"
